/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier_18 (
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] multi
  );
  
  
  
  reg [15:0] operand;
  
  always @* begin
    operand[0+15-:16] = a * b;
    multi[0+7-:8] = operand[0+7-:8];
  end
endmodule
