/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_15 (
    input [7:0] a,
    input [7:0] b,
    input alufn,
    output reg [7:0] result,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [8:0] operand;
  
  always @* begin
    if (alufn == 1'h0) begin
      operand = a + b;
    end else begin
      operand = a - b;
    end
    z = (operand[0+7-:8] == 1'h0);
    v = ((a[7+0-:1] == 1'h0) & (alufn ^ b[7+0-:1] == 1'h0) & (operand[7+0-:1] == 1'h1)) | ((a[7+0-:1] == 1'h1) & (alufn ^ b[7+0-:1] == 1'h1) & (operand[7+0-:1] == 1'h0));
    n = operand[7+0-:1];
    result = operand[0+7-:8];
  end
endmodule
