/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module beam_tracker_1 (
    input [8:0] ldr,
    output reg [3:0] beam_position
  );
  
  
  
  reg [3:0] pos;
  
  always @* begin
    pos = 4'hf;
    
    case (ldr)
      9'h001: begin
        pos = 1'h0;
      end
      9'h002: begin
        pos = 1'h1;
      end
      9'h004: begin
        pos = 2'h2;
      end
      9'h008: begin
        pos = 3'h4;
      end
      9'h010: begin
        pos = 3'h5;
      end
      9'h020: begin
        pos = 3'h7;
      end
      9'h040: begin
        pos = 4'h8;
      end
      9'h080: begin
        pos = 4'h9;
      end
      9'h100: begin
        pos = 4'ha;
      end
    endcase
    beam_position = pos;
  end
endmodule
