/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_16 (
    output reg compareout,
    input z,
    input v,
    input n,
    input [1:0] alufn
  );
  
  
  
  always @* begin
    
    case (alufn)
      2'h1: begin
        compareout = (z);
      end
      2'h2: begin
        compareout = (n ^ v);
      end
      2'h3: begin
        compareout = (z | (n ^ v));
      end
      default: begin
        compareout = 1'h0;
      end
    endcase
  end
endmodule
